# Generated by Django 5.2.5 on 2026-04-14 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_passwords', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartpassword',
            name='length',
            field=models.PositiveSmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(12)]),
        ),
    ]
