# Generated by Django 5.2.5 on 2026-05-05 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_passwords', '0003_alter_smartpassword_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartpassword',
            name='length',
            field=models.PositiveSmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(12, message='Password length must be at least 12 characters'), django.core.validators.MaxValueValidator(100, message='Password length cannot exceed 100 characters')]),
        ),
    ]
